# Generated by Django 3.2 on 2021-12-28 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_friendly_name_category_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
